export const data = [
    {
        id: 1,
        src: "https://st.imageinstant.net/data/comics/32/vo-luyen-dinh-phong.jpg",
        name: "Võ luyện đỉnh phong",
        category: [ "Hành động", "Hoat Hinh",],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 10,
        description: "Võ đạo đỉnh phong, là cô độc, là tịch mịch, là dài đằng đẵng cầu tác, là cao xử bất thắng hàn Phát triển trong nghịch cảnh, cầu sinh nơi tuyệt địa, bất khuất không buông tha, mới có thể có thể phá võ chi cực đạo. Lăng Tiêu các thí luyện đệ tử kiêm quét rác gã sai vặt Dương Khai ngẫu lấy được một bản vô tự hắc thư, từ nay về sau đạp vào dài đằng đẵng võ đạo.",
        comicImage: [
            "https://images2.imgbox.com/40/5b/ipK5XwSg_o.jpg",
            "https://images2.imgbox.com/34/5a/Uge0Ak6D_o.jpg",
            "https://images2.imgbox.com/7d/8d/bkUAsI19_o.jpg",
            "https://images2.imgbox.com/13/09/3Cl0fS4e_o.jpg",
            "https://images2.imgbox.com/c4/46/lkvVMnov_o.jpg",
            "https://images2.imgbox.com/fe/57/91Le62Kd_o.jpg",
            "https://images2.imgbox.com/06/81/PI0NnyUw_o.jpg",
            "https://images2.imgbox.com/79/09/Kxm8k9mr_o.jpg",
            "https://images2.imgbox.com/4a/e5/7bhhsxV7_o.jpg",
            "https://images2.imgbox.com/39/61/sfeq9OaM_o.jpg",
            "https://gapo-image.s3-ap-southeast-1.amazonaws.com/images/81534805-9189-4629-a52f-adf33d641afc.jpeg",
            "https://images2.imgbox.com/74/7d/47e1Ue8D_o.jpg",
            "https://images2.imgbox.com/4f/e7/tzvS5Dmk_o.jpg",
            "https://images2.imgbox.com/25/e7/Ew2JveCF_o.jpg",
            "https://images2.imgbox.com/ce/4e/XJ6igRGD_o.jpg",
            "https://gapo-image.s3-ap-southeast-1.amazonaws.com/images/85d7976b-b524-406f-a520-3d019243cd65.jpeg",
            "https://images2.imgbox.com/f3/7a/q8HfZWL5_o.jpg",
    ]
    },
    {
        id: 2,
        src: "//st.imageinstant.net/data/comics/61/toi-cuong-phan-sao-lo-he-thong.jpg",
        name: "Tối cường phản sáo lộ hệ thống",
        category: [ "Hành động", "Hoat Hinh",],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 9,
        description: "Người trẻ tuổi, năm đó ta bắt đầu Trang Bức thời điểm, các ngươi còn chỉ là một giọt chất lỏng!Tiên tử, theo tại hạ đi một chuyến, bảo đảm mang ngươi Trang Bức mang ngươi bay, mang ngươi đồng thời khà khà khà! Người mặc cuồng đồ áo giáp, kiên khiêng nhật viêm đấu bồng. Tay trái Vô Tẫn Chi Nhận, tay phải Tru Tiên Thần Kiếm. Quét ngang Tu Tiên Giới không có địch thủ, liền hỏi một tiếng còn có ai? Trang Bức Như Phong, thường bạn ta thân! Đường dài dài đằng đẵng, Trang Bức làm bạn! Từ Khuyết bước lên một cái Trang Bức con đường, mỗi ngày không phải ở Trang Bức, chính là ở đi Trang Bức trên đường!",
        comicImage: [
            "https://images8.intercomics.club/vnstory/f9/72/f9729b7a6d652b103976cfcaa2cc28f9.webp",
            "https://images8.intercomics.club/vnstory/67/70/67708c4aec352e25f69d72fc6c01e655.webp",
            "https://images8.intercomics.club/vnstory/4a/ae/4aae890d61bb92165056f106a0c0e00d.webp",
            "https://images8.intercomics.club/vnstory/8c/a4/8ca4fcb62498f60ce469b894b0d0d47d.webp",
            "https://images8.intercomics.club/vnstory/49/b9/49b9c1edf8a912d1ca013be68395275a.webp",
            "https://images8.intercomics.club/vnstory/a8/c5/a8c5de0ea34225b71c2bb5ca5d213501.webp",
            "https://images8.intercomics.club/vnstory/21/87/2187c37e454fba8dd825c000b5678926.webp",
            "https://images8.intercomics.club/vnstory/8e/35/8e3549cab5c102e994ac3fa1ca35b149.webp",


    ]
    },
    {
        id: 3,
        src: "//st.imageinstant.net/data/comics/214/van-gioi-tien-tung.jpg",
        name: "Vạn giới tiên tung",
        category: [ "Hành động", "Phiêu lưu", "Harrem", "Truyện màu", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 8,
        description: "Mỗi bông hoa là 1 thế giới, Phàm thế chỉ là một hạt cát bé nhỏ trong tay tiên ma Tiên ma nhất niệm, nhân thế vạn năm Sông núi vạn dặm cũng chỉ là kính hoa thủy nguyệt Con người có 3 hồn 7 phách, sau khi chết hồn sẽ quay về bầu trời sao vạn giới Nơi sâu của trời sao, chính là đàn tràng của tiên ma trong truyền thuyết",
        comicImage: [
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegKMn5godmnTWoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegBhFFviqQ6IGoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegcmsgxEsqnzyoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegczydWEdi7nWoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://server.truyendoc.info/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegsJLJHwdn0HGoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6Cyegwchh6fqBHMWoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegSLbIUmnZStVhruoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegICxiCkP506yoW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6Cyegj5MJHG2KL1ioW4y9P1FkSYp4iEUmnZcjmKIr045WT64b9M=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6Cyeg5SKAa36ku6Aa36DhoIf7gSlWq0loCLafKZUmnZEDteiAt6Wz46fE=",
            "http://server.truyendoc.info/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegJCTHJ1dGzkUIf7gSlWq0loCLafKZUmnZEDteiAt6Wz46fE=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcq3S9TAT6CyegPlAa36aRNtqUmnZbAIf7gSlWq0loCLafKZUmnZEDteiAt6Wz46fE=",
            
    ]
    },
    {
        id: 4,
        src: "	http://st.imageinstant.net/data/comics/199/van-toc-chi-kiep.jpg",
        name: "Vạn tộc chi kiếp",
        category: [ "Hành động","Truyện màu", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 4,
        description: "Chưa cập nhật",
        comicImage: [
            "https://cdn.statically.io/img/image.wcomic.site/vol_3/images/post/w_4335/c_359513/i_9893003.jpg?data=wcomic",
            "https://cdn.statically.io/img/image.wcomic.site/vol_3/images/post/w_4335/c_359513/i_9893004.jpg?data=wcomic",
            "https://cdn.statically.io/img/image.wcomic.site/vol_3/images/post/w_4335/c_359513/i_9893005.jpg?data=wcomic",
            "https://cdn.statically.io/img/image.wcomic.site/vol_3/images/post/w_4335/c_359513/i_9893006.jpg?data=wcomic",
            "https://cdn.statically.io/img/image.wcomic.site/vol_3/images/post/w_4335/c_359513/i_9893007.jpg?data=wcomic",
    ]
    },
    {
        id: 5,
        src: "//st.imageinstant.net/data/comics/231/chien-hon-tuyet-the.jpg",
        name: "Chiến hồn tuyệt thế",
        category: [ "Hành động", "Phiêu lưu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 5,
        description: "Sau khi linh khí hồi phục, mọi người chắt chiu từng tơ linh khí, chỉ có Lữ Thụ, dựa vào hệ thống điểm cảm xúc tiêu cực , oán hận người khác là trở nên mạnh hơn! Cậu ta chỉ muốn bảo vệ em gái, nhưng mà thời kì lũ lụt khó có thể tránh khỏi, chỉ đành..... tiện oán hận người khác , trở nên mạnh hơn! Vậy thì , chuẩn bị xong chưa, Lữ Thụ Đại Ma Vương  tới đây",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 6,
        src: "//st.imageinstant.net/data/comics/213/trong-sinh-do-thi-tu-tien.jpg",
        name: "Trọng sinh đô thị tu Tiên",
        category: [ "Hành động", "Phiêu lưu", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 5,
        description: "Truyện Trọng Sinh Đô Thị Tu Tiên được chuyển thể từ tiểu thuyết cùng tên của tác giả Thập Lý Kiếm ThầnBắc Huyền Tiên Tôn Trần Phàm do tu hành quá nhanh mà độ kiếp thất bại. Trở về thời niên thiếu ở trái đất, pháp bảo, thần thông, tiên khí đều không còn. Hắn nhớ lại ân oán tình thù ngày trước, quyết tâm đền bù đầy đủ, tu hành một thế, trúc vô thượng đạo cơ, rũ sạch tâm ma... thành tựu Chân Tiên đại đạo",
        comicImage: [
            "https://images8.intercomics.club/vnstory/08/ee/08ee67881d94c65013f4e5617e356522.webp",
            "https://images8.intercomics.club/vnstory/a8/3b/a83b50de8a2014bca6b5696db5eb5c6d.webp",
            "https://images8.intercomics.club/vnstory/0c/ab/0cab152d18e8b3c8e66894d2518ff2ef.webp",
            "https://images8.intercomics.club/vnstory/fa/67/fa675708c6eeddf065ad56aa30009133.webp",
            "https://images8.intercomics.club/vnstory/6f/84/6f8487acd6ec3f5302bc09d9d1b82ac4.webp",
            "https://images8.intercomics.club/vnstory/98/c7/98c7fa4234cfdf202b72d73b8536deab.webp",
            "https://images8.intercomics.club/vnstory/40/81/4081d768508c0aa24514c08527bc6932.webp",
            "https://images8.intercomics.club/vnstory/27/d0/27d0c779236861e6fcb8e893bcacd453.webp",
            "https://images8.intercomics.club/vnstory/7e/83/7e83cd776ee641d3a449617a4a5aea37.webp",
            "https://images8.intercomics.club/vnstory/3e/c3/3ec35a8f554bc74e216a45663ffe3fca.webp",
            "https://images8.intercomics.club/vnstory/66/da/66daacb354b57a898b7e3cba4b7c5d9f.webp",
            "https://images8.intercomics.club/vnstory/d1/d9/d1d9159fe1381138bf5691ea097eba67.webp",
        ]
    },
    {
        id: 7,
        src: "//st.imageinstant.net/data/comics/201/doi-truong-linh-danh-thue.jpg",
        name: "Đội trưởng lính đánh thuê",
        category: [ "Hành động", "Hoat Hinh", "Drama", "Truyện màu", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đã xong",
        rate: 5,
        description: "Câu chuyện về biệt đội đánh thuê Pháp, Kang Chan anh ta được gọi là God of Blackfield bởi đồng đội và kẻ thù. Tuy nhiên sau một nhiệm vụ tiêu diệt Massallan của phiến quân SISS, Kang Chan đã chết bởi một viên đạn của một kẻ phản bội trong hàng ngũ quân của anh ta, anh đã chết nhưng lại được cứu bởi một thế lực bí ẩn và tỉnh dậy sau 3 năm tại Hàn Quốc. Tuy nhiên anh lại trong cơ thể một Kang Chan khác, một học sinh trung học 19 tuổi đang bị bắt nạt. Hành trình tìm ra kẻ phản bội và tìm ra sự thật đằng sau sự tái sinh của anh chính thức bắt đầu khi bạn bấm vào xem và like.",
        comicImage: [
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5KMn5godmnTWoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5BhFFviqQ6IGoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5cmsgxEsqnzyoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5czydWEdi7nWoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5sJLJHwdn0HGoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5wchh6fqBHMWoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5SLbIUmnZStVhruoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://cdn.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5ICxiCkP506yoW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",
            "http://proxy.doctruyentranh.online/image-comic/viJ2qmRjqxnj3TSdHDZcqUmnZTSPvh0nRU5j5MJHG2KL1ioW4y9P1FkSYp4iEUmnZcjmKIgljUXHUmnZEytk=",

        ]
    },
    {
        id: 8,
        src: "//st.imageinstant.net/data/comics/167/jitsu-wa-ore-saikyou-deshita.jpg",
        name: "Jitsu wa Ore, Saikyou deshita?",
        category: [ "Hành động", "Hoat Hinh", "Chuyển sinh"],
        author:"Akahashi Ai",
        status: "Đang tiến hành",
        rate: 6,
        description: "Một thanh niên bị bắt nạt được tái sinh ở thế giới khác và cuộc sống bình yên của cậu bắt đầu lại từ đầu...",
        comicImage: [
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/001.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/003.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/002.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/005.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/004.jpg",
        ]
    },
    {
        id: 9,
        src: "//st.imageinstant.net/data/comics/240/return-survival.jpg",
        name: "RETURN SURVIVAL",
        category: [ "Hành động", "Hoat Hinh", "Chuyển sinh", "Truyện màu", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 6,
        description: "Main được trọng sinh về trước ngày tận thế vài tháng",
        comicImage: [
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/001.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/003.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/002.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/005.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/004.jpg",
        ]
    },
    {
        id: 10,
        src: "//st.imageinstant.net/data/comics/98/vo-dang-ky-hiep.jpg",
        name: "Võ đang kỳ hiệp",
        category: [ "Hành động", "Hoat Hinh", "Chuyển sinh", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 6,
        description: "Main được trọng sinh về trước khi bị phản bội",
        comicImage: [
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/001.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/003.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/002.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/005.jpg",
            "https://image.rawdevart.com/comic/jitsu-wa-ore-saikyou-deshita/chapters/1/004.jpg",
        ]
    },
    {
        id: 11,
        src: "//st.imageinstant.net/data/comics/234/dai-tuong-vo-hinh.jpg",
        name: "Đại tượng vô hình",
        category: [ "Hành động", "Phiêu lưu", "Horror", "Truyện màu", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 7,
        description: "Nữ chính trong một lần tai nạn xe bị sinh vật bí ẩn gá vào người, sau khi tỉnh lại đến một thế giới yêu linh. Trong lúc cô ấy sợ hãi, tuyệt vọng thì xuất hiện một thiếu niên cứu cô ta về hiện thế. Thì ra thế giới này có yêu linh, sinh vật trong cơ thể cô ta là yêu linh tên Nhân Tiêu, không cách nào đẩy yêu linh ra ngoài được, cùng đồng hành trên con đường trừ yêu...",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 12,
        src: "//st.imageinstant.net/data/comics/153/nguyen-long.jpg",
        name: "Nguyên long",
        category: [ "Hành động", "Phiêu lưu", "Cổ đại", "Truyện màu", "ManhWa"],
        author:"Bizon",
        status: "Đang tiến hành",
        rate: 7,
        description: "Nguyên Hồn thế giới, huyền huyễn thần kỳ, gia tộc bộc phát, tông môn đứng vững, cường giả phân ra, cao thủ như mây.Vương bài tay đánh lén Vương Thắng xuyên qua đến Nguyên Hồn thế giới, đâm đầu vào không đủ tư cách nhất cá chép tàn hồn, thành người gặp người bắt nạt phế vật. Ta tới là giết người, không phải đến bị các ngươi cười nhạo.",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 13,
        src: "//st.imageinstant.net/data/comics/60/nguoi-xau.jpg",
        name: "Người xấu",
        category: [ "Hành động", "Học đường", "Webtoon", "ManhWa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 7,
        description: "Để trở thành hình mẫu lý tưởng của người con gái ấy, trong suốt 10 năm qua tôi đã diễn vai thanh niên tốt bụng tới mức được gọi là thiên thần! Tuy nhiên, cô ấy lại nói rằng mình thích trai hư và trai tốt là một bọn cực kì nhàm chán... Vậy thì ngay từ hôm nay, tôi chẳng cần phải diễn làm gì nữa! Tôi sẽ trở lại với con người thật của mình - một kẻ xấu chính hiệu!",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 14,
        src: "//st.imageinstant.net/data/comics/231/chien-hon-tuyet-the.jpg",
        name: "Chiến hồn tuyệt thế",
        category: [ "Hành động", "Phiêu lưu", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 8,
        description: "Main được trọng sinh về trước khi bị phản bội",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 15,
        src: "//st.imageinstant.net/data/comics/148/ta-bi-nhot-tai-cung-mot-ngay-muoi-van-na-5986.jpg",
        name: "Ta bị nhốt ở đây 10 vạn năm",
        category: [ "Hành động", "Phiêu lưu", "Chuyển sinh", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 8,
        description: "Đang cập nhật",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 16,
        src: "//st.imageinstant.net/data/comics/127/toan-chuc-phap-su.jpg",
        name: "Toàn chức pháp sư ",
        category: [ "Hành động", "Manhwa", "Bí ẩn", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 8,
        description: "Tỉnh lại sau giấc ngủ, thế giới đại biến. Quen thuộc cao trung truyền thụ chính là phép thuật, nói cho mọi người muốn trở thành một tên xuất sắc Ma Pháp Sư. Ở lại đô thị ở ngoài du đãng tập kích nhân loại ma vật yêu thú, mắt nhìn chằm chằm. Tôn trọng khoa học thế giới đã biến thành tôn trọng phép thuật, một mực có như nhau lấy học tra đối xử giáo viên của chính mình, như nhau ánh mắt dị dạng bạn học, như nhau xã hội tầng dưới chót giãy dụa ba ba, như nhau thuần mỹ nhưng không thể bước đi không phải huyết thống muội muội... Bất quá, Mạc Phàm phát hiện tuyệt đại đa số người đều chỉ có thể chủ tu nhất hệ phép thuật, chính mình nhưng là toàn hệ toàn năng pháp sư!",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 17,
        src: "//st.imageinstant.net/data/comics/146/nguyen-ton.jpg",
        name: "Nguyên tôn",
        category: [ "Hành động", "Manhwa", "Fantasy", "Truyện màu", "Phiêu lưu"],
        author:"Thiên Tằm Thổ Đậu",
        status: "Đang tiến hành",
        rate: 5,
        description: "Một tác phẩm mới của Thiên Tằm Thổ Đậu Ta có một ngụm Huyền Hoàng Khí, có thể nuốt thiên địa nhật nguyệt tinh. ......... Lúc đó đường về, đã là một con đường vận mệnh treo ngược. Ngày xưa vinh hoa, như thay đổi khôn lường, một giấc ác mộng dài. Thiếu niên chấp bút, Long Xà bay động. Là vì một vòng quang mang bổ ra dáng vẻ nặng nề chi loạn thế, vấn đỉnh điện ngọc thương khung. Đường báo thù, cùng ta đồng hành. Một ngụm Huyền Hoàng chân khí nhất định nuốt thiên địa nhật nguyệt tinh thần, hùng thị cỏ cây thương sinh. Thiết họa tịch chiếu, vụ ải ngân câu, bút tẩu du long xông Cửu Châu. Hoành tư thiên hạ, mực vẩy thanh sơn, thôn tính biển hồ nạp trăm sông.",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 18,
        src: "//st.imageinstant.net/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg",
        name: "Hệt như hàn quang gặp nắng gắt",
        category: [ "Manhwa", "Ngôn tình", "Chuyển sinh", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 4,
        description: "[Cập nhật thứ 4 và chủ nhật hàng tuần] Nữ hài nghịch công lược băng sơn tổng tài. Vườn trường ? Chức trường ? Tư muội ? Tôi đều có thể",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 19,
        src: "//st.imageinstant.net/data/comics/80/di-toc-trung-sinh.jpg",
        name: "Dị tộc trùng sinh",
        category: [ "Hành động", "Manhua", "Truyện màu"],
        author:"Dị Hoàng Trùng Sinh",
        status: "Đang tiến hành",
        rate: 6,
        description: "Năm 2023, linh khí thức tỉnh, mọi ngóc ngách trên thế giới đều bị bao bọc bởi linh khí nồng đậm, các sinh vật cũng không tránh khỏi bị ảnh hưởng. Loài người thức tỉnh bắt đầu có được năng lượng mạnh mẽ, những sinh vật khác bị ảnh hưởng bởi linh khí cũng tiến hóa thần tốc. Chuỗi thức ăn một lần nữa xáo trộn, loài người đã không còn là kẻ thống trị trên địa cầu. Trên trái đất xuất hiện những khu vực mà nhân loại không có cách nào tiến vào, một vài chủng tộc cường đại thần bí âm thầm trỗi dậy, một trong những thế lực đứng hàng truyền thuyết trong đó là... Dị Hoàng tộc Một vương tử của dị hoàng tộc bị giam lỏng trong cung điện của mình, bất ngờ tai nạn xảy ra,sau khi hắn chết đi đã được chuyển sinh sang cơ thể của một nhân loại, điều đáng nói là chủ nhân cơ thể này là một tên phế vật. Vị vương tử với tính cách ngáo ngơ này sẽ tạo lên những sóng gió gì trong thời đại linh khí... hãy cùng tìm câu trả lời.",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 20,
        src: "//st.imageinstant.net/data/comics/180/dai-chua-te.jpg",
        name: "Đại chúa tể",
        category: [ "Hành động", "Manhua", "Truyện màu"],
        author:"Thiên Tằm Thổ Đậu",
        status: "Đang tiến hành",
        rate: 3,
        description: "Đại thế giới, vị diện giao hội, vạn tộc mọc lên san sát như rừng, quần hùng tập trung, một vị từ tương lai Hạ vị diện đích Thiên chi Chí tôn, tại đây Vô Tận Thế Giới, diễn lại làm cho người hướng tới Truyền Kỳ, truy cầu lấy cái kia chúa tể chi lộ.Vô tận hỏa vực, Viêm Đế chấp chưởng, Vạn Hỏa đốt Thương Khung.Võ Cảnh ở trong, Vũ tổ chi uy, chấn nhiếp Càn Khôn.Tây Thiên chi điện, bách chiến chi hoàng, chiến uy không thể địch.Bắc Hoang chi khâu, Vạn Mộ chi địa, Bất Tử chi chủ trấn Thiên địa.",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 21,
        src: "//st.imageinstant.net/data/comics/220/ban-hoc-cua-toi-la-linh-danh-thue.jpg",
        name: "Bạn học của tôi là lính đánh thuê",
        category: [ "Hành động", "Phiêu lưu",  "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 2,
        description: "Yu Ijin - người duy nhất sống sót sau một vụ tai nạn máy bay thảm khốc khi anh còn nhỏ. Sau quãng thời gian 10 năm trở thành lính đánh thuê để hoàn thành giao kèo với người đã cứu mình, cậu đã trở về với gia đình ở quê hương. Một cuộc sống mới và cả sóng gió mới bắt đầu...",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 22,
        src: "//st.imageinstant.net/data/comics/234/tien-de-xam-nhap.jpg",
        name: "Tiên đế xâm nhập",
        category: [ "Hành động", "Phiêu lưu", "Xuyên không", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 3,
        description: "Đang cập nhật",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 23,
        src: "//st.imageinstant.net/data/comics/183/than-hon-vo-de.jpg",
        name: "Thần hồn võ đế",
        category: [ "Manhua", "Phiêu lưu", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 2,
        description: "Đang cập nhật",
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 24,
        src: "//st.imageinstant.net/data/comics/18/tinh-vo-than-quyet.jpg",
        name: "Tinh võ thần quyết",
        category: [ "Hành động", "Phiêu lưu", "Truyện màu"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 3,
        description: "Quyền toái nhật nguyệt, chưởng thôn sơn hàĐạp nghịch thiên cường giả lộ, mỹ nhân làm bạn, tu luyện tinh võ truyền thừa, chấp chưởng quyền hành bát phương, thành tựu thần vương tối caoTừ thiếu nữ thiên tài ôn nhu, đáng yêu, quận chúa thân hình nóng bỏng tràn trề đến yêu tộc mỹ nữ thần bí, cao hơn nữa là nữ võ thần trong truyền thuyết tối cao...Một con đường ngộ đạo không tịch mịch, một truyền kỳ đầy sắc thái."
        ,
        comicImage: [
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
            "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
        ]
    },
    {
        id: 25,
        src: "//st.imageinstant.net/data/comics/228/ta-lap-hau-cung-tai-tay-du-ky.jpg",
        name: "Ta lập hậu cung tại tây du ký",
        category: [ "Manhua", "Phiêu lưu", "Chuyển sinh", "Truyện màu","Xuyên không"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate: 3,
        description: "Sinh viên năm 4 trần thạc, hiện đang là thực tập cho một công ty video tiktok, ngoài ý muốn tài khoản video ngắn của hắn trói buộc vào hệ thống tây du ký. Có thể tùy ý xuyên qua thế giới tây du và hiện đại"
    ,
    comicImage: [
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
    ]
    },
    {
        id: 26,
        src: "//st.imageinstant.net/data/comics/220/toi-la-nguoi-choi-than-chu-don-doc.jpg",
        name: "Tôi là người chơi thần chú đơn độc",
        category: [ "Hành động", "Phiêu lưu", "Fantasy", "Truyện màu", "Manhwa"],
        author:"Đang cập nhật",
        status: "Đang tiến hành",
        rate:  3,
        description: "Park Do Hyeok người đang sống như một người làm công ăn lương bình thường đã trở thành người được thức tỉnh đúng như mong muốn trong thời khắc rơi vào khủng hoảng tuyệt vọng! Những kỉ niệm và kinh nghiệm trong trò chơi mà dành cả cuộc đời 20 tuổi đã trở thành năng lực thức tỉnh!! Hơn nữa, từ bây giờ hoạt động sôi nổi kì dị có một không hai của Park Do Hyeok người chơi thần chú nhắm tới đỉnh cao thế giới ‘người được thức tỉnh đến tận Triple’ với tỉ lệ 1/1 tỉ đã được bắt đầu."
    ,
    comicImage: [
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5108387.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7289929.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/7706704.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/1813337.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4558486.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/5926466.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/143419.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/4397834.jpg",
        "https://i1.manhuarock.com/file/i1mhrock/storage/230/0/9908420.jpg",
    ]
    },
]
